server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cuilei192/springcloud-config-pub.git
          search-paths:
          username: cuilei192
          password: 1992cuilei
          default-label: master
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.204.130:8761/eureka/
